package com.example.project.queryExecutor;

public enum QueryExecutorType {
    COM_EXAMPLE_PROJECT_QUERYEXECUTOR_IMPLS_ELASTICQUERYEXECUTOR,
    COM_EXAMPLE_PROJECT_QUERYEXECUTOR_IMPLS_HIVEQUERYEXECUTOR,
    COM_EXAMPLE_PROJECT_QUERYEXECUTOR_IMPLS_IMPALAQUERYEXECUTOR,
    COM_EXAMPLE_PROJECT_QUERYEXECUTOR_IMPLS_SQLSERVERQUERYEXECUTOR
}
